# ML-03 — Frame Your Lane as an ML Task

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/AzramAfaq/flyrank-ml-internship/blob/main/work/notebooks/w02_ml_task_framing.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane as an ML task (type)

*Classification, clustering, ranking, or scoring — which one, and why?*

In [1]:
import os, sys, subprocess
import pandas as pd

IN_COLAB = "google.colab" in sys.modules
REPO_URL = "https://github.com/AzramAfaq/flyrank-ml-internship"
REPO_DIR = "flyrank-ml-internship"

if IN_COLAB:
    if not os.path.isdir(REPO_DIR):
        subprocess.run(["git", "clone", "--depth", "1", REPO_URL, REPO_DIR], check=True)
    os.chdir(REPO_DIR)
else:
    while not os.path.isdir("data/raw") and os.getcwd() != "/":
        os.chdir("..")

DATA_PATH = "data/raw/content_refresh_anonymized.csv"
df = pd.read_csv(DATA_PATH)
print("Loaded:", DATA_PATH)
print("Shape (rows, cols):", df.shape)

Loaded: data/raw/content_refresh_anonymized.csv
Shape (rows, cols): (30000, 44)

In [2]:
df

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.00,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.00,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.00,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.00,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.00,good,page_3_5,down,-34.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,content_c322796023c8,client_e29c9c180c,10.0,0.05,LOW,0.00,keyword article,transactional,1386.0,9084.0,...,8000-15000,0.00,0.0,0.00,0.00,0.00,low,top_3,new,NaN
29996,content_526572edb3fa,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,2654.0,17056.0,...,15000-25000,0.39,6.6,0.00,66.67,0.00,moderate,page_1,down,-75.1
29997,content_38112bdd0c6e,client_349c41201b,10.0,1.00,HIGH,0.00,keyword article,transactional,2857.0,18725.0,...,15000-25000,0.19,4.1,0.00,0.00,0.00,good,page_1,down,-66.2
29998,content_ab26273a7e7a,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,transactional,NaN,NaN,...,NaN,0.22,6.0,1.73,4.06,0.00,excellent,page_1,down,-27.9
29999,content_887020f20b5e,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,commercial,4124.0,26315.0,...,25000+,1.89,8.4,6.58,3.31,2.63,good,page_1,stable,12.3

## 2. Target or proxy

*What would you predict? Where does that label come from — observed outcome or a defined rule?*

we predict how much a page's traffic is changing, and we got that number ourselves from two real time periods already in the data — not from a shortcut label.

In [3]:
scoped = df[(df["avg_position"] > 0) & (df["impressions_prev_30d"] > 0)].copy()

In [4]:
scoped

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.00,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.00,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.00,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.00,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.00,good,page_3_5,down,-34.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29994,content_995627a1f490,client_7f2253d7e2,70.0,0.05,LOW,0.00,keyword article,transactional,2801.0,18452.0,...,15000-25000,0.86,4.6,0.00,16.67,0.00,moderate,page_1,down,-65.8
29996,content_526572edb3fa,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,2654.0,17056.0,...,15000-25000,0.39,6.6,0.00,66.67,0.00,moderate,page_1,down,-75.1
29997,content_38112bdd0c6e,client_349c41201b,10.0,1.00,HIGH,0.00,keyword article,transactional,2857.0,18725.0,...,15000-25000,0.19,4.1,0.00,0.00,0.00,good,page_1,down,-66.2
29998,content_ab26273a7e7a,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,transactional,NaN,NaN,...,NaN,0.22,6.0,1.73,4.06,0.00,excellent,page_1,down,-27.9
29999,content_887020f20b5e,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,commercial,4124.0,26315.0,...,25000+,1.89,8.4,6.58,3.31,2.63,good,page_1,stable,12.3

In [5]:
scoped["impr_change_pct"] = (scoped["impressions_last_30d"] - scoped["impressions_prev_30d"]) / scoped["impressions_prev_30d"]

In [7]:
scoped["impr_change_pct"].describe()

count    26604.000000
mean        -0.047614
std          4.739306
min         -1.000000
25%         -0.626110
50%         -0.334442
75%          0.000000
max        449.000000
Name: impr_change_pct, dtype: float64

In [8]:
print(f"Share with ANY decline (<0%): {(scoped['impr_change_pct'] < 0).mean():.1%}")

Share with ANY decline (<0%): 74.1%

In [9]:
print(f"Share with a >10% decline: {(scoped['impr_change_pct'] < -0.10).mean():.1%}")

Share with a >10% decline: 68.6%

## 3. Success metric

*One metric you can defend. What number means 'good'?*

A simple rule based on one obvious factor (word count) scores 0% precision — it's no better than picking pages at random. That's because decline isn't driven by any single factor alone; it comes from a combination of weak signals (search volume, competition, staleness, etc. — remember, we checked these earlier and each had near-zero correlation on its own). Only a model that can weigh multiple signals together has a chance of finding the real decliners.

In [10]:
ranked = scoped.sort_values("impr_change_pct")

In [11]:
ranked

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct,impr_change_pct
23297,content_60d81e7dd1eb,client_8527a891e2,10.0,0.00,LOW,0.00,keyword article,commercial,1872.0,11972.0,...,0.00,21.3,0.00,0.00,0.0,low,page_3_5,down,-100.0,-1.000000
1220,content_327bbfd6df97,client_624b60c58c,NaN,NaN,NaN,NaN,feedly article,NaN,4458.0,29937.0,...,0.00,5.7,0.00,0.00,100.0,low,page_1,down,-100.0,-1.000000
12495,content_edcd521f4135,client_a88a7902cb,30.0,0.29,LOW,0.12,keyword article,commercial,2957.0,19356.0,...,0.00,7.2,11.11,5.88,0.0,moderate,page_1,down,-100.0,-1.000000
12459,content_1451d55fa92a,client_a88a7902cb,0.0,0.00,LOW,0.00,keyword article,informational,4529.0,31100.0,...,0.00,11.3,0.00,0.00,0.0,low,striking,down,-100.0,-1.000000
12434,content_5b9cd5b2818a,client_8527a891e2,0.0,0.00,LOW,0.00,keyword article,informational,1713.0,10776.0,...,0.00,56.1,0.00,0.00,0.0,low,deep,down,-100.0,-1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19697,content_4f1966b37335,client_b4944c6ff0,10.0,0.24,LOW,0.00,keyword article,commercial,2637.0,19088.0,...,0.16,6.4,14.29,14.29,0.0,good,page_1,up,17077.8,170.777778
3561,content_22f4d2f58c42,client_434c9b5ae5,0.0,0.00,LOW,0.00,keyword article,informational,2917.0,19893.0,...,0.00,13.1,6.25,6.25,0.0,low,striking,up,21400.0,214.000000
14549,content_d020d42e7fcc,client_b4944c6ff0,10.0,1.00,HIGH,1.60,keyword article,commercial,2835.0,20955.0,...,0.08,2.1,0.00,0.00,0.0,moderate,top_3,up,26166.7,261.666667
15405,content_a023517539fe,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,informational,3530.0,22134.0,...,0.01,85.8,3.40,3.61,0.0,excellent,deep,up,27907.3,279.072655
24695,content_dd882c4152ac,client_a88a7902cb,70.0,0.01,LOW,0.00,keyword article,transactional,2844.0,19232.0,...,0.00,75.5,0.00,75.00,0.0,moderate,deep,up,44900.0,449.000000

In [12]:
ranked[["content_id", "search_volume", "content_type", "impr_change_pct"]].head(10)

                 content_id  search_volume     content_type  impr_change_pct
23297  content_60d81e7dd1eb           10.0  keyword article             -1.0
1220   content_327bbfd6df97            NaN   feedly article             -1.0
12495  content_edcd521f4135           30.0  keyword article             -1.0
12459  content_1451d55fa92a            0.0  keyword article             -1.0
12434  content_5b9cd5b2818a            0.0  keyword article             -1.0
12440  content_bcc1e8e2646d            0.0  keyword article             -1.0
12583  content_7f7d3a9330bd           30.0  keyword article             -1.0
12554  content_32f84f608abe           50.0  keyword article             -1.0
23396  content_cb0b2b24814f         1300.0  keyword article             -1.0
23361  content_631387373820           20.0  keyword article             -1.0

In [13]:
(ranked["impr_change_pct"] == -1.0).sum()

np.int64(1390)

In [14]:
ranked = scoped.sort_values(["impr_change_pct", "impressions_prev_30d"], ascending=[True, False])

In [16]:
ranked[["content_id", "search_volume", "impressions_prev_30d", "impr_change_pct"]].head(10)

,content_id,search_volume,impressions_prev_30d,impr_change_pct
2786,content_331a01416e92,20.0,1966,-1.0
831,content_e74933316051,NaN,799,-1.0
19865,content_123b5d750cbc,NaN,364,-1.0
27111,content_8679ea39fb73,40.0,291,-1.0
4279,content_e7e76918dd38,NaN,235,-1.0
19472,content_6c5a581c33ce,20.0,232,-1.0
26706,content_36979e112d48,NaN,207,-1.0
28455,content_506693a2cdd2,1300.0,204,-1.0
17693,content_d4d39a028c6b,10.0,202,-1.0
16875,content_b15e7fc3936f,NaN,185,-1.0

In [17]:
true_worst = set(ranked.head(100)["content_id"])

In [18]:
naive_guess = set(scoped.sort_values("word_count").head(100)["content_id"])

In [19]:
len(naive_guess & true_worst)

0

In [20]:
import random
random_guess = set(random.sample(list(scoped["content_id"]), 100))
len(random_guess & true_worst)

2

## 4. The unit of analysis, as a real dataframe

*Load your lane's slice and show it: one row = one what?*
Unit of analysis: one row = one piece of published content (one article/page),
tracked over a 90-day window. Each row is identified by content_id (the specific
page) and client_id (which website it belongs to). All the other columns
(word count, impressions, clicks, trend, etc.) describe that single page.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

In [21]:
scoped.shape

(26604, 45)

In [22]:
scoped.iloc[0]

content_id                content_304f48230142
client_id                    client_f369cb89fc
search_volume                             10.0
competition                               0.67
competition_level                         HIGH
cpc                                       2.05
content_type                   keyword article
main_intent                      transactional
word_count                              3221.0
char_count                             20457.0
provider_used                              NaN
model_used                    gemini-2.5-flash
impressions_90d                           3803
clicks_90d                                  29
pageviews_90d                               22
sessions_90d                                17
users_90d                                   16
engaged_sessions_90d                         1
ai_sessions_90d                              0
scroll_events_90d                            1
days_with_impressions                       88
days_with_sessions                          13
impressions_last_30d                       578
clicks_last_30d                              2
sessions_last_30d                            2
impressions_prev_30d                       987
clicks_prev_30d                             13
sessions_prev_30d                            9
content_age_days                           187
age_tier                               181-365
age_tier_order                               5
days_since_last_update                      20
freshness_tier                            0-30
word_count_tier                      2000-3500
char_count_tier                    15000-25000
ctr                                       0.76
avg_position                              10.6
engagement_rate                           5.88
scroll_rate                               4.55
ai_traffic_pct                             0.0
impression_tier                           good
position_tier                         striking
trend_direction                           down
trend_pct                                -41.4
impr_change_pct                      -0.414387
Name: 0, dtype: object

## 5. Why ML beats a fixed rule here

*What makes the pattern too messy for an if-statement?*

Why ML beats a fixed rule here: Individually, none of the obvious factors
(search volume, competition, word count, content age, days since last update)
correlate meaningfully with decline. A naive fixed rule ("shortest articles are
the worst decliners") scored 0/100 precision@100 - worse than a random baseline,
which scored 2/100. This shows decline isn't explained by any single factor, but
by combinations of weak signals interacting together - which is exactly the kind
of pattern ML models can learn and a fixed rule cannot.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

Self-check:
- Task type: Ranking/scoring (not yes/no classification) - the goal is an
  ordered priority list of pages, not a single label.
- Target: Built my own honest target (impr_change_pct) by comparing real
  traffic between two time windows, instead of reusing the dataset's built-in
  label - avoids circularity.
- Success metric: precision@100 - of the top 100 pages flagged, how many are
  genuinely among the true worst decliners.
- Unit of analysis: one row = one page (content_id), tracked over 90 days.
- Why ML: a naive single-factor rule scored 0/100 (worse than random's 2/100),
  proving decline depends on combinations of weak signals, not any one factor -
  which only ML can learn.